from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

MODELS_DIR = PROJECT_ROOT / "models"

RESULTS_DIR = PROJECT_ROOT / "results"
BACKTEST_DIR = RESULTS_DIR / "backtest"
FIGURES_DIR = RESULTS_DIR / "figures"
METRICS_DIR = RESULTS_DIR / "metrics"

NOTEBOOKS_DIR = PROJECT_ROOT / "notebooks"

RAW_DATA_PATH = RAW_DATA_DIR / "cac40_2017_2022.csv"
PROCESSED_DATA_PATH = PROCESSED_DATA_DIR / "cac40_features.csv"
MODEL_PATH = MODELS_DIR / "cac40_ffnn.keras"


TICKER = "^FCHI"

START_DATE = "2017-01-01"
END_DATE = "2022-01-01"


RETURN_1D_PERIOD = 1
RETURN_8D_PERIOD = 8

ADX_PERIOD = 20
RSI_PERIOD = 20

STOCH_FASTK_PERIOD = 14
STOCH_SLOWK_PERIOD = 3

CCI_PERIOD = 20

VOLATILITY_WINDOW = 10


TRAIN_RATIO = 0.80

RANDOM_SEED = 42

DROPOUT_RATE = 0.15

BATCH_SIZE = 64
EPOCHS = 25

PREDICTION_THRESHOLD = 0.50

INITIAL_CAPITAL = 10_000.0
TRANSACTION_COST_BPS = 0.0

TRADING_DAYS_PER_YEAR = 252
RISK_FREE_RATE = 0.0